console.log('hi');

const allCountries = document.querySelectorAll('path');
const h1 = document.querySelector('h1');




const countryMap = new Map([
    ['Afghanistan', 'AF'],
    ['Angola', 'AO'],
    ['Albania', 'AL'],
    ['United Arab Emirates', 'AE'],
    ['Argentina', 'AR'],
    ['Armenia', 'AM'],
    ['Australia', 'AU'],
    ['Austria', 'AT'],
    ['Azerbaijan', 'AZ'],
    ['Burundi', 'BI'],
    ['Belgium', 'BE'],
    ['Benin', 'BJ'],
    ['Burkina Faso', 'BF'],
    ['Bangladesh', 'BD'],
    ['Bulgaria', 'BG'],
    ['Bosnia and Herzegovina', 'BA'],
    ['Belarus', 'BY'],
    ['Belize', 'BZ'],
    ['Bolivia', 'BO'],
    ['Brazil', 'BR'],
    ['Brunei Darussalam', 'BN'],
    ['Bhutan', 'BT'],
    ['Botswana', 'BW'],
    ['Central African Republic', 'CF'],
    ['Canada', 'CA'],
    ['Switzerland', 'CH'],
    ['China', 'CN'],
    ['Côte d\'Ivoire', 'CI'],
    ['Cameroon', 'CM'],
    ['Democratic Republic of the Congo', 'CD'],
    ['Republic of Congo', 'CG'],
    ['Colombia', 'CO'],
    ['Costa Rica', 'CR'],
    ['Chile', 'CL'],
    ['Cuba', 'CU'],
    ['Czech Republic', 'CZ'],
    ['Germany', 'DE'],
    ['Djibouti', 'DJ'],
    ['Denmark', 'DK'],
    ['Dominican Republic', 'DO'],
    ['Algeria', 'DZ'],
    ['Ecuador', 'EC'],
    ['Egypt', 'EG'],
    ['Eritrea', 'ER'],
    ['Estonia', 'EE'],
    ['Ethiopia', 'ET'],
    ['Finland', 'FI'],
    ['Gabon', 'GA'],
    ['United Kingdom', 'GB'],
    ['Georgia', 'GE'],
    ['Ghana', 'GH'],
    ['Guinea', 'GN'],
    ['The Gambia', 'GM'],
    ['Guinea-Bissau', 'GW'],
    ['Equatorial Guinea', 'GQ'],
    ['Greece', 'GR'],
    ['Greenland', 'GL'],
    ['Guatemala', 'GT'],
    ['Guyana', 'GY'],
    ['Honduras', 'HN'],
    ['Croatia', 'HR'],
    ['Haiti', 'HT'],
    ['Hungary', 'HU'],
    ['Indonesia', 'ID'],
    ['India', 'IN'],
    ['Ireland', 'IE'],
    ['Iran', 'IR'],
    ['Iraq', 'IQ'],
    ['Iceland', 'IS'],
    ['Israel', 'IL'],
    ['Italy', 'IT'],
    ['Jamaica', 'JM'],
    ['Jordan', 'JO'],
    ['Japan', 'JP'],
    ['Kazakhstan', 'KZ'],
    ['Kosovo', 'XK'],
    ['Serbia', 'RS'],
    ['Kenya', 'KE'],
    ['Kyrgyzstan', 'KG'],
    ['Cambodia', 'KH'],
    ['Republic of Korea', 'KR'],
    ['Kuwait', 'KW'],
    ['Lao PDR', 'LA'],
    ['Lebanon', 'LB'],
    ['Liberia', 'LR'],
    ['Libya', 'LY'],
    ['Sri Lanka', 'LK'],
    ['Lesotho', 'LS'],
    ['Lithuania', 'LT'],
    ['Luxembourg', 'LU'],
    ['Latvia', 'LV'],
    ['Morocco', 'MA'],
    ['Moldova', 'MD'],
    ['Madagascar', 'MG'],
    ['Mexico', 'MX'],
    ['Macedonia', 'MK'],
    ['Mali', 'ML'],
    ['Myanmar', 'MM'],
    ['Montenegro', 'ME'],
    ['Mongolia', 'MN'],
    ['Mozambique', 'MZ'],
    ['Mauritania', 'MR'],
    ['Malawi', 'MW'],
    ['Malaysia', 'MY'],
    ['Namibia', 'NA'],
    ['New Caledonia', 'NC'],
    ['Niger', 'NE'],
    ['Nigeria', 'NG'],
    ['Nicaragua', 'NI'],
    ['Netherlands', 'NL'],
    ['Norway', 'NO'],
    ['Nepal', 'NP'],
    ['New Zealand', 'NZ'],
    ['Oman', 'OM'],
    ['Pakistan', 'PK'],
    ['Panama', 'PA'],
    ['Peru', 'PE'],
    ['Philippines', 'PH'],
    ['Papua New Guinea', 'PG'],
    ['Poland', 'PL'],
    ['Puerto Rico', 'PR'],
    ['Dem. Rep. Korea', 'KP'],
    ['Portugal', 'PT'],
    ['Paraguay', 'PY'],
    ['Qatar', 'QA'],
    ['Romania', 'RO'],
    ['Russian Federation', 'RU'],
    ['Rwanda', 'RW'],
    ['Western Sahara', 'EH'],
    ['Saudi Arabia', 'SA'],
    ['Sudan', 'SD'],
    ['South Sudan', 'SS'],
    ['Senegal', 'SN'],
    ['Sierra Leone', 'SL'],
    ['El Salvador', 'SV'],
    ['Somaliland', 'XS'],
    ['Somalia', 'SO'],
    ['Republic of Serbia', 'RS'],
    ['Suriname', 'SR'],
    ['Slovakia', 'SK'],
    ['Slovenia', 'SI'],
    ['Sweden', 'SE'],
    ['Swaziland', 'SZ'],
    ['Syria', 'SY'],
    ['Chad', 'TD'],
    ['Togo', 'TG'],
    ['Thailand', 'TH'],
    ['Tajikistan', 'TJ'],
    ['Turkmenistan', 'TM'],
    ['East Timor', 'TL'],
    ['Trinidad and Tobago', 'TT'],
    ['Tunisia', 'TN'],
    ['Turkey', 'TR'],
    ['Taiwan', 'TW'],
    ['Tanzania', 'TZ'],
    ['Uganda', 'UG'],
    ['Ukraine', 'UA'],
    ['Uruguay', 'UY'],
    ['United States', 'US'],
    ['Uzbekistan', 'UZ'],
    ['Venezuela', 'VE'],
    ['Vietnam', 'VN'],
    ['Vanuatu', 'VU'],
    ['Yemen', 'YE'],
    ['South Africa', 'ZA'],
    ['Zambia', 'ZM'],
    ['Zimbabwe', 'ZW'],
    ['Anguilla', 'AI'],
    ['Aruba', 'AW'],
    ['Bermuda', 'BM'],
    ['France', 'FR'],
    ['Spain', 'ES'],
    ['British Virgin Islands', 'VG'],
    ['Cayman Islands', 'KY'],
    ['Comoros', 'KM'],
    ['Curaçao', 'CW'],
    ['Falkland Islands', 'FK'],
    ['Faroe Islands', 'FO'],
    ['French Guiana', 'GF'],
    ['Gibraltar', 'GI'],
    ['Greenland', 'GL'],
    ['Guadeloupe', 'GP'],
    ['Guam', 'GU'],
    ['Martinique', 'MQ'],
    ['Mayotte', 'YT'],
    ['Montserrat', 'MS'],
    ['Nauru', 'NR'],
    ['New Caledonia', 'NC'],
    ['Northern Mariana Islands', 'MP'],
    ['Palau', 'PW'],
    ['Puerto Rico', 'PR'],
    ['Réunion', 'RE'],
    ['Saint Barthélemy', 'BL'],
    ['Saint Martin', 'MF'],
    ['Saint Pierre and Miquelon', 'PM'],
    ['Saba', 'BQ'],
    ['Saint Eustatius', 'BQ'],
    ['Seychelles', 'SC'],
    ['Solomon Islands', 'SB'],
    ['Somalia', 'SO'],
    ['South Georgia and the South Sandwich Islands', 'GS'],
    ['Turks and Caicos Islands', 'TC'],
    ['United States Virgin Islands', 'VI'],
    ['Wallis and Futuna Islands', 'WF'],

]);





const set = new Set();
allCountries.forEach((country) => {
    set.add(country.classList.value);
});



const nameClickEvent =  (e) => {
    h1.textContent = '';
    h1.textContent = e.target.classList.value;
    const countryCode = countryMap.get(e.target.classList.value);
   
    const geoNameData = 
        fetch(`http://api.geonames.org/countryInfoJSON?formatted=true&lang=it&country=${countryCode}&username=rhar763&style=full`)
        .then(response => response.json());
    const wordBankData =  
        fetch(`http://api.worldbank.org/v2/country/${countryCode}?format=json`)
        .then(response => response.json());
    Promise.all([geoNameData, wordBankData])
        .then((data) => {
            console.log(data[0].geonames[0].population, data[1][1][0].incomeLevel);
            //create a modal on right hand of screen that displays the data;



        });
}
 
allCountries.forEach((country) => {
    country.addEventListener('click', nameClickEvent);
});
